name: Update Version and Tag

on:
  release:
    types: [created]

jobs:
  update-version:
    runs-on: ubuntu-latest
    env:
      TAG_VERSION: ${{ github.ref_name }} 
      BRANCH_NAME: update-tag-version-${{ github.ref_name }}
    steps:
      # Step 1: Checkout the original repository's code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Git with official account
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Update Version/version file
      - name: Update version file
        run: |
          echo "${{ env.TAG_VERSION }}" > Version/version

      # Step 4: Commit and push changes
      - name: Commit and push changes
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}
          git add Version/version
          git commit -m "Update version to ${{ env.TAG_VERSION }}"
          git push origin ${{ env.BRANCH_NAME }}

      # Step 5: Create and push tag
      - name: Create and push tag
        run: |
          git tag ${{ env.TAG_VERSION }}
          git push origin ${{ env.TAG_VERSION }}