name: Non-English Comments Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  non-english-comments-check:
    runs-on: ubuntu-latest

    env:
      # Directories to be excluded
      EXCLUDE_DIRS: ".git docs tests scripts assets node_modules build"
      # Files to be excluded (e.g., markdown, text files)
      EXCLUDE_FILES: "*.md *.txt *.html *.css *.min.js *.mdx"

    steps:
      - uses: actions/checkout@v4

      - name: Search for Non-English comments
        run: |
          set -e
          # Define the regex pattern to match Chinese characters
          pattern='[\p{Han}]'

          # Process the directories to be excluded
          exclude_dirs=""
          for dir in $EXCLUDE_DIRS; do
            exclude_dirs="$exclude_dirs --exclude-dir=$dir"
          done

          # Process the file types to be excluded
          exclude_files=""
          for file in $EXCLUDE_FILES; do
            exclude_files="$exclude_files --exclude=$file"
          done

          # Use grep to find all comments containing Non-English characters
          # Check if the file matches the excluded patterns in EXCLUDE_FILES
          grep -Pnr "$pattern" . $exclude_dirs $exclude_files | while read -r line ; do
            # Extract the filename from the line
            file_name=$(echo "$line" | cut -d':' -f1)
            
            # Skip the file if it matches any pattern in EXCLUDE_FILES
            for file_pattern in $EXCLUDE_FILES; do
              if echo "$file_name" | grep -q "$file_pattern"; then
                continue 2
              fi
            done
            
            # Write the result to the non_english_comments.txt file
            echo "$line" >> non_english_comments.txt
          done || true

      - name: Output non-English comments if found
        run: |
          if [ -s non_english_comments.txt ]; then
            echo "Non-English comments found in the following locations:"
            cat non_english_comments.txt
            exit 1  # terminate the workflow
          else
            echo "No Non-English comments found."
          fi

      # If there are non-English comments, the CI process will terminate
      # It will provide the specific file and line number for quick navigation
