name: Merge for Closed Milestone PRs

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      milestone:
        description: 'Milestone name to collect closed PRs from'
        required: true
        default: 'v3.8.2'  # Default milestone set to v3.8.2
      target_branch:
        description: 'Target branch to merge the consolidated PR'
        required: true
        default: 'pre-release-v3.8.2'  # Default target branch with pre-release-v*.*.* format
  schedule:
    - cron: '0 0 * * 0'  # Scheduled to run every Sunday at 00:00 UTC

jobs:
  cherry_pick_closed_milestone_prs:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Git user details for making commits
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Fetch closed PRs from the specified milestone using GitHub API and parse with a script
      - name: Fetch and Filter Closed PRs
        id: fetch_prs
        run: |
          milestone="${{ github.event.inputs.milestone }}"
          target_branch="${{ github.event.inputs.target_branch }}"
          
          # Fetch closed PRs for the specified milestone
          prs=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github+json" \
                "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&milestone=$milestone")

          # Parse PR numbers and merge commits
          echo "$prs" | grep '"number":\|"merge_commit_sha":' | while read -r line; do
            if [[ $line == *'"number":'* ]]; then
              pr_number=$(echo "$line" | grep -o '[0-9]\+')
            elif [[ $line == *'"merge_commit_sha":'* ]]; then
              merge_commit=$(echo "$line" | grep -o '[a-f0-9]\{40\}')
              
              # Skip if merge_commit is empty or null
              if [[ -n "$merge_commit" ]]; then
                echo "PR #$pr_number with commit $merge_commit ready for cherry-pick"
                echo "$pr_number:$merge_commit" >> pr_commits.txt
              fi
            fi
          done
          
          # Show parsed PRs and commits
          echo "Parsed PRs and Commits:"
          cat pr_commits.txt || echo "No PRs found for milestone."

      # Step 4: Create a new branch from main, cherry-pick PRs, and push to remote
      - name: Create and Cherry-pick Branch
        if: ${{ steps.fetch_prs.outputs.prs }} != "[]"
        run: |
          cherry_pick_branch="milestone-cherry-pick-$(date +%Y%m%d%H%M%S)"
          target_branch="${{ github.event.inputs.target_branch }}"

          # Verify and fetch the latest for the target branch
          git fetch origin $target_branch:$target_branch || exit 1
          
          # Switch to main branch, pull latest changes, then create a new cherry-pick branch
          git checkout main
          git pull origin main
          git checkout -b $cherry_pick_branch

          # Read each PR and its merge commit, cherry-pick if not in target branch
          touch conflict_commits.txt
          while IFS=: read -r pr_number merge_commit; do
            if git merge-base --is-ancestor $merge_commit $target_branch 2>/dev/null; then
              echo "Skipping PR #$pr_number - Commit $merge_commit already in $target_branch"
            else
              echo "Cherry-picking PR #$pr_number with commit $merge_commit"
              if ! git cherry-pick $merge_commit; then
                echo "Conflict in PR #$pr_number - Commit $merge_commit. Logging and continuing."
                echo "$pr_number:$merge_commit" >> conflict_commits.txt
                git cherry-pick --abort
              fi
            fi
          done < pr_commits.txt

          # Push the cherry-pick branch to the remote repository
          git push origin $cherry_pick_branch

          # Display any conflicts encountered
          if [[ -s conflict_commits.txt ]]; then
            echo "The following commits encountered conflicts during cherry-pick:"
            cat conflict_commits.txt
          fi

      # Step 5: Create a single pull request to merge the cherry-pick branch into the target branch
      - name: Create Pull Request to Target Branch
        if: ${{ steps.fetch_prs.outputs.prs }} != "[]"
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: $cherry_pick_branch
          base: ${{ github.event.inputs.target_branch }}
          title: "Consolidated Closed Milestone PRs for ${{ github.event.inputs.target_branch }}"
          body: |
            This PR includes all cherry-picked changes from closed PRs in milestone '${{ github.event.inputs.milestone }}' to ${{ github.event.inputs.target_branch }}.
            
            The following commits encountered conflicts during cherry-pick:
            $(cat conflict_commits.txt || echo "No conflicts.")
