name: Reopen and Update Stale Issues

on:
  workflow_dispatch: # 手动触发

jobs:
  reopen_stale_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Closed Issues with lifecycle/stale Label
        id: fetch_issues
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          script: |
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              labels: 'lifecycle/stale',
              per_page: 100
            });

            return JSON.stringify(issues.map(issue => issue.number));
          result-encoding: string

      - name: Reopen and Remove Label
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          script: |
            const issueNumbers = JSON.parse(`{{ steps.fetch_issues.outputs.result }}`);

            for (const issue_number of issueNumbers) {
              // Reopen the issue
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number,
                state: 'open'
              });
              console.log(`Reopened issue #${issue_number}`);

              // Remove the lifecycle/stale label
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number,
                name: 'lifecycle/stale'
              });
              console.log(`Removed label 'lifecycle/stale' from issue #${issue_number}`);
            }