name: Check for Chinese Comments

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_chinese_comments:
    runs-on: ubuntu-latest

    env:
      # 定义要排除的目录
      EXCLUDE_DIRS: '.git,docs,tests,scripts,assets,node_modules,build'
      # 定义要排除的文件类型
      EXCLUDE_FILES: '*.md,*.txt,*.html,*.css,*.min.js'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Search for Chinese comments
      run: |
        set -e
        # 定义正则表达式模式匹配中文字符
        pattern='[\p{Han}]'

        # 将 EXCLUDE_DIRS 和 EXCLUDE_FILES 分别处理为 grep 的参数
        exclude_dir_args=$(echo $EXCLUDE_DIRS | sed 's/,/ --exclude-dir=/g' | sed 's/^/--exclude-dir=/')
        exclude_file_args=$(echo $EXCLUDE_FILES | sed 's/,/ --exclude=/g' | sed 's/^/--exclude=/')

        # 使用 grep 查找所有包含中文字符的注释并保存到文件
        grep -Pnr "$pattern" . $exclude_dir_args $exclude_file_args > chinese_comments.txt || true

    - name: Output and fail if Chinese comments are found
      run: |
        if [ -s chinese_comments.txt ]; then
          echo "Chinese comments found in the following locations:"
          cat chinese_comments.txt
          exit 1  # 标记为失败并终止整个工作流
        else
          echo "No Chinese comments found."
        fi
