name: Update version file on tag

on:
  push:
    tags:
      - 'v*.*.*'  # 只有符合 v*.*.* 格式的 tag 才会触发

jobs:
  update_version_file:
    runs-on: ubuntu-latest
    env:
      TAG_VERSION: ${{ github.ref_name }}  # 获取当前 tag 版本号

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史记录，确保我们可以推送

      # Step 2: Update version file
      - name: Update version file
        run: |
          echo "${{ env.TAG_VERSION }}" > version/version  # 将 tag 写入 version 文件

      # Step 3: Commit the change
      - name: Commit version file change
        run: |
          git add version/version
          git commit -m "Update version to ${{ env.TAG_VERSION }}"

      # Step 4: Push the change to the repository
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GITHUB_TOKEN 进行身份验证
          branch: main  # 推送到主分支