name: Upgrade version by tag

permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  upgrade_version:
    runs-on: ubuntu-latest
    env:
      TAG_VERSION: ${{ github.ref_name }}  # 使用GitHub提供的ref_name来捕获tag名称
      BRANCH_NAME: update-version-${{ github.ref_name }}  # 设置BRANCH_NAME为新的版本分支
    steps:
      # Step 1: Checkout the original repository's code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: openimsdk/actions-test  # 替换为正确的仓库
          fetch-depth: 0

      # Step 2: Set up Git with official account
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # # Step 3: Create a new branch for version update
      # - name: Create new branch for version update
      #   run: |
      #     git checkout -b ${{ env.BRANCH_NAME }}

           # Step 4: Update version file
      - name: Update version file
        run: |
          echo "${{ env.TAG_VERSION }}" > version/version

      # # Step 4: Update version file
      # - name: Update version file
      #   run: |
      #     echo "${{ env.TAG_VERSION }}" > version/version
      #     git add version/version
      #     git commit -m "Update version to ${{ env.TAG_VERSION }}"

      # # Step 5: Push the new branch to the repository
      # - name: Push to repository
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GITHUB_TOKEN 进行身份验证
      #   run: |
      #     git push origin ${{ env.BRANCH_NAME }}

      # Step 6: Create a Pull Request from the new branch to the original repository
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v7.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          # token: ${{ secrets.BOT_TOKEN }} 
          commit-message: "Update version to ${{ env.TAG_VERSION }}"
          branch: ${{ env.BRANCH_NAME }}
          base: main  # 原始仓库的目标分支
          title: "Update version to ${{ env.TAG_VERSION }}"
          body: "This PR updates the version file to the new tag version ${{ env.TAG_VERSION }}."
